/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */


plugins {
    java
}

group = "com.example"
version = "0.1.0-SNAPSHOT"

repositories {
    mavenCentral()
    maven {
        name = "papermc"
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.10-R0.1-SNAPSHOT")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

tasks.register<org.gradle.api.tasks.javadoc.Javadoc>("generateJavadoc") {
    source = sourceSets["main"].allJava
    classpath = sourceSets["main"].compileClasspath
    // Use 'destinationDir' for older Gradle versions
    destinationDir = file("$buildDir/docs/javadoc")
}


